### ISSUE TITLE
New package builds forthcoming?

### ISSUE THREAD

**Issue by mleklund** [theforeman/smart_proxy_dns_powerdns#16]
ruby-smart-proxy-dns-powerdns-0.2.0-1 package for ubuntu has the broken PTR record issue, fixed in 3686169a09616bdd6ec3f6249763aee1fd495eb8

**Comment by ekohl** [comment]
Yes, thanks for reminding me.

**Comment by ekohl** [comment]
I pushed [0.2.1](https://rubygems.org/gems/smart_proxy_dns_powerdns/versions/0.2.1). For Debian nightly I submitted https://github.com/theforeman/foreman-packaging/pull/1115. I'll also create a PR against 1.11-stable and update https://github.com/theforeman/foreman-packaging/pull/1033 once I tested that.

**Comment by mmoll** [comment]
@ekohl the 0.2.1 tag is missing in the repo.

**Comment by ekohl** [comment]
@mmoll forgot that, thanks.

**Comment by ekohl** [comment]
The builds were pushed.
