### ISSUE TITLE
RPM install: uninitialized constant Proxy::Dns::Record - in foreman-proxy logs for Foreman 1.12.0

### ISSUE THREAD

**Issue by robertlupinek** [theforeman/smart_proxy_dns_powerdns#17]
I'm getting the following error in the foreman-proxy logs on CentOS 7.2 box running Foreman 1.12.0.

`ERROR -- : Couldn't enable 'dns_powerdns': uninitialized constant Proxy::Dns::Record`

I am using the rpm installation  which results with this version of the package:

`Installed Packages
rubygem-smart_proxy_dns_powerdns.noarch                                  0.1.0-1.el7                @foreman-plugins`

I will happily provide any other test you would like me perform.

Good news is the latest gem install worked just fine when performing the upgrade.  

I did have to refresh the active features for the smart proxy before the dns proxy became available in my domains:

![image](https://cloud.githubusercontent.com/assets/6145651/16920032/07546e72-4cda-11e6-9576-e3e259c7de17.png)

**Comment by ekohl** [comment]
I failed to update the RPMs in time because I didn't have time to properly test it. Currently this is blocked on https://github.com/theforeman/foreman-packaging/pull/1033

**Comment by mmoll** [comment]
this should be ok now?

**Comment by ekohl** [comment]
You're right, this was fixed.
