### ISSUE TITLE
CNAME support

### ISSUE THREAD

**Issue by mleklund** [theforeman/smart_proxy_dns_powerdns#18]
1.13 seems to be adding CNAME support for dns_cmd and nsupdate.  Can we expect support for powerdns?

**Comment by ekohl** [comment]
That certainly sounds interesting and I'll add this soon. For my personal reference, https://github.com/theforeman/smart-proxy/commit/2b498a4a96f84d4dffb16a52a1862a44d0a60eba added the support.

**Comment by ekohl** [comment]
Sorry it took so long, but the support is there now. Note that Foreman itself still doesn't use this functionality so it's just for those who directly use the smart proxy API.
