### ISSUE TITLE
Please support powerdns REST API

### ISSUE THREAD

**Issue by ruben-herold** [theforeman/smart_proxy_dns_powerdns#19]
hi,

since powerdns 4.0 the rest api is stable. Please don't use direct database access any more!!!!
This will break things like dnssec and so on....

**Comment by ekohl** [comment]
Thanks for reminding me that https://github.com/theforeman/smart_proxy_dns_powerdns/pull/15 needs finishing.

**Comment by ekohl** [comment]
I did some initial testing on this but I'd appreciate any further testing before making a final release.
