### ISSUE TITLE
rest suppport

### ISSUE THREAD

**Issue by anc86** [theforeman/smart_proxy_dns_powerdns#21]
Hello,
on debian 8, I have installed plugin from foreman repository, but got error "Couldn't enable 'dns_powerdns': Parameter 'powerdns_backend' is expected to be one of mysql,postgresql,dummy"
I want to use REST backend. 
Any advice ?

**Comment by anc86** [comment]
I see it was added just recently, how to have latest version installed

**Comment by dmitri-d** [comment]
A version of smart_proxy_dns_powerdns rubygem containing support for rest backend has yet to be released. 

You'll either need to update bundler file to use gem source (see http://bundler.io/git.html), or build the gem locally (pls. see http://guides.rubygems.org/make-your-own-gem/).

**Comment by ekohl** [comment]
The rest support is currently only available in the git version. I'll try to make a new release soon. There are instructions to install from Gems in https://theforeman.org/plugins/ but you should note that those are for Foreman, not Foreman Proxy. It will work the same, but the paths will be different.

**Comment by anc86** [comment]
thanks guys, I have added /usr/share/foreman-proxy/bundler.d/Gemfile.local.rb with
gem 'smart_proxy_dns_powerdns', :git => "https://github.com/theforeman/smart_proxy_dns_powerdns.git"

Then I run bundle update smart_proxy_dns_powerdns, but keep getting error 
Could not locate Gemfile


what is my mistake ?

**Comment by anc86** [comment]
was able to build gem and install. now I have to figure out how to use add. how to add dns record through foreman ?

**Comment by anc86** [comment]
now I realized that it's still useless with bind backend, I could've just use one of sql options.

**Comment by anc86** [comment]
worked great with mysql backend

**Comment by ekohl** [comment]
Good to know!
