### ISSUE TITLE
Update SOA serial

### ISSUE THREAD

**Issue by stevie-** [theforeman/smart_proxy_dns_powerdns#22]
Hello,

powerdns 4.0.1
mysql 5.7

we are using foreman_proxy to add or delete A records to powerdns mysql backend in a Master / Slave setup.
Adding or Removing of entries work on master db, but SOA serial is not updated for zones. So changes are not visible to slaves.

https://doc.powerdns.com/md/authoritative/dnsupdate/#soa-serial-updates

For adding an entry a unix timestamp should be set on `change_date`. Thus people could use auto serial function from powerdns.

But this doesn't work for deletes.

Other way is to call `pdnsutil increase-serial $ZONE$` which would work for any change, but IIRC breaks auto-serial.

**Comment by ekohl** [comment]
I've only used PowerDNS together with database replication so I didn't think of this. I'll look into this, but first I will focus on making a new release which supports the API. My intention will be to make that the preferred backend.

**Comment by j-vizcaino** [comment]
I am experiencing the same problem here, except I am using PowerDNS 3.4 and direct modification of MySQL.
SOA serial number is not incremented.

EDIT: looking at the code there is no function taking care of updating the SOA record every time a record is added/updated/deleted. When using Bind, `rndc` takes care of updating the SOA for us. This has to be done explicitly here.
