### ISSUE TITLE
postgresql support

### ISSUE THREAD

**Issue by brechsteiner** [theforeman/smart_proxy_dns_powerdns#5]
It would be nice to have database support for postgresql.

**Comment by ekohl** [comment]
I certainly agree. In the future I would also like to support the REST API. In the following 2 weeks I intend to package it first and then have a look at multiple backends.

**Comment by brechsteiner** [comment]
sorry when i ask again but how does it look like the database support? Should i make a pull request with a suggestion?

**Comment by brechsteiner** [comment]
sorry for that

**Comment by ekohl** [comment]
A pull request would be great. I did manage to get it packaged for Debian, but I'm lacking time to build support for multiple databases.

**Comment by ekohl** [comment]
I opened https://github.com/theforeman/smart_proxy_dns_powerdns/pull/8 where I started by factoring out mysql to a backend class. It's still very much work in progress, but it's a start.

**Comment by ekohl** [comment]
Fixed in https://github.com/theforeman/smart_proxy_dns_powerdns/commit/6793c34b1c2966b6ba3a59ced6c34aa3c30399a8
