### ISSUE TITLE
Missing file when installing from gem

### ISSUE THREAD

**Issue by dgagnon** [theforeman/smart_proxy_dns_powerdns#6]
The following error occurs:

D, [2015-10-06T14:39:49.614060 #5382] DEBUG -- : Unable to find dependency 'dns_powerdns' of 'dns'.:/usr/share/foreman-proxy/lib/proxy/pluggable.rb:49:in `block in validate_prerequisites_enabled!'
/usr/share/foreman-proxy/lib/proxy/pluggable.rb:47:in`each'
/usr/share/foreman-proxy/lib/proxy/pluggable.rb:47:in `validate_prerequisites_enabled!'
/usr/share/foreman-proxy/lib/proxy/pluggable.rb:38:in`validate!'
/usr/share/foreman-proxy/lib/proxy/plugin.rb:134:in `configure_plugin'
/usr/share/foreman-proxy/lib/proxy/plugin.rb:28:in`block in configure_loaded_plugins'
/usr/share/foreman-proxy/lib/proxy/plugin.rb:28:in `each'
/usr/share/foreman-proxy/lib/proxy/plugin.rb:28:in`configure_loaded_plugins'
/usr/share/foreman-proxy/lib/launcher.rb:101:in `launch'
/usr/share/foreman-proxy/bin/smart-proxy:6:in`<main>'

When installing through gem.  You need to manually add the following file:

root@test:/usr/share/foreman-proxy# cat /usr/share/foreman-proxy/bundler.d/dns_powerdns.rb
gem 'smart_proxy_dns_powerdns'

**Comment by domcleal** [comment]
This'll just have to be documented somewhere, since a gem can't add the file to this path.  Packages will work properly.
